services:
  - type: web
    name: molgenweb
    runtime: python
    env: python
    plan: free
    region: oregon
    pythonVersion: "3.12.0"
    buildCommand: pip install --upgrade pip && pip install --only-binary :all: -r requirements.txt && python -c "from transformers import AutoTokenizer, AutoModelForCausalLM; AutoTokenizer.from_pretrained('ncfrey/ChemGPT-4.7M'); AutoModelForCausalLM.from_pretrained('ncfrey/ChemGPT-4.7M')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MODEL_NAME
        value: ncfrey/ChemGPT-4.7M
